### ISSUE TITLE
Error in GimpFu (gi.FunctionInfo)

### ISSUE THREAD

**Issue by joserick** [bootchk/GimpFu-v3#2]
Hello,

I tried to run an example of [helloworld.py](https://gimpbook.com/scripting/gimp-script-templates/helloworld.py) and other plugins but I always get the following error:

![imagen](https://user-images.githubusercontent.com/15143699/159193437-86f942ad-340e-4b82-8e44-628d34eda250.png)

Could you help me to solve or comment what is the reason for the error.

**Comment by bootchk** [comment]
Sorry to be late.  GimpFu is experimental, meaning I can't devote much time to it.

It probably is a bug in GimpFu.  
Probably "Gimp.locale_directory" is of type "function" where it should be of type "string."
In other words, the code is passing a function, where it should call the function to get a string, and then pass the string.
That is just my first guess.

I will explore more.   I have never see this error when I use GimpFu, so I don't understand what is different for you.

**Comment by bootchk** [comment]
Yes,  a bug in my code, which I fixed.  Thanks for reporting it.  It take it use use a language other than English, which I had never tested.

**Comment by joserick** [comment]
Thank you very much!
